In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("employee_data.csv")

In [3]:
df.head()

,Employee_ID,Age,Gender,Department,Job_Role,Monthly_Income,Years_at_Company,Performance_Rating,Project_Count,No. of Companies Worked
0,1,58,Female,IT,Manager,154.88,15,4,6,3
1,2,48,Female,Sales,Assistant,130.79,6,1,2,2
2,3,34,Male,Marketing,Assistant,137.44,24,1,6,3
3,4,27,Female,Marketing,Manager,680.90,10,4,9,3
4,5,40,Male,Marketing,Executive,102.06,29,1,3,3

In [4]:
df.tail()

,Employee_ID,Age,Gender,Department,Job_Role,Monthly_Income,Years_at_Company,Performance_Rating,Project_Count,No. of Companies Worked
95,96,28,Male,HR,Analyst,710.30,7,2,4,2
96,97,27,Female,IT,Assistant,507.60,6,4,7,3
97,98,31,Female,Marketing,Assistant,599.40,22,3,9,2
98,99,53,Female,Marketing,Executive,674.40,23,3,5,3
99,100,52,Male,IT,Analyst,174.66,3,1,2,4

In [9]:
df.describe()

,Employee_ID,Age,Monthly_Income,Years_at_Company,Performance_Rating,Project_Count,No. of Companies Worked
count,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000
mean,50.500000,38.790000,337.966300,13.940000,2.42000,5.200000,2.630000
std,29.011492,11.556008,274.506007,8.348253,1.07478,2.741378,1.116045
min,1.000000,20.000000,101.480000,1.000000,1.00000,1.000000,1.000000
25%,25.750000,28.000000,140.387500,6.750000,2.00000,2.000000,2.000000
50%,50.500000,39.500000,179.465000,13.000000,2.00000,6.000000,3.000000
75%,75.250000,47.250000,533.350000,22.000000,3.00000,8.000000,4.000000
max,100.000000,59.000000,975.400000,29.000000,4.00000,9.000000,4.000000

In [6]:
df.shape

(100, 10)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Employee_ID              100 non-null    int64
 1   Age                      100 non-null    int64
 2   Gender                   100 non-null    object
 3   Department               100 non-null    object
 4   Job_Role                 100 non-null    object
 5   Monthly_Income           100 non-null    float64
 6   Years_at_Company         100 non-null    int64
 7   Performance_Rating       100 non-null    int64
 8   Project_Count            100 non-null    int64
 9   No. of Companies Worked  100 non-null    int64
dtypes: float64(1), int64(6), object(3)
memory usage: 7.9+ KB

In [10]:
df.dtypes

Employee_ID                  int64
Age                          int64
Gender                      object
Department                  object
Job_Role                    object
Monthly_Income             float64
Years_at_Company             int64
Performance_Rating           int64
Project_Count                int64
No. of Companies Worked      int64
dtype: object

In [13]:
df.columns

Index(['Employee_ID', 'Age', 'Gender', 'Department', 'Job_Role',
       'Monthly_Income', 'Years_at_Company', 'Performance_Rating',
       'Project_Count', 'No. of Companies Worked'],
      dtype='object')

In [14]:
# Add Gender Column
val=['Female','Female','Male','Male','Male']
df.loc[:4,'Gender']=val

In [15]:
df.head()

,Employee_ID,Age,Gender,Department,Job_Role,Monthly_Income,Years_at_Company,Performance_Rating,Project_Count,No. of Companies Worked
0,1,58,Female,IT,Manager,154.88,15,4,6,3
1,2,48,Female,Sales,Assistant,130.79,6,1,2,2
2,3,34,Male,Marketing,Assistant,137.44,24,1,6,3
3,4,27,Male,Marketing,Manager,680.90,10,4,9,3
4,5,40,Male,Marketing,Executive,102.06,29,1,3,3

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])

In [17]:
df

,Employee_ID,Age,Gender,Department,Job_Role,Monthly_Income,Years_at_Company,Performance_Rating,Project_Count,No. of Companies Worked
0,1,58,0,IT,Manager,154.88,15,4,6,3
1,2,48,0,Sales,Assistant,130.79,6,1,2,2
2,3,34,1,Marketing,Assistant,137.44,24,1,6,3
3,4,27,1,Marketing,Manager,680.90,10,4,9,3
4,5,40,1,Marketing,Executive,102.06,29,1,3,3
...,...,...,...,...,...,...,...,...,...,...
95,96,28,1,HR,Analyst,710.30,7,2,4,2
96,97,27,0,IT,Assistant,507.60,6,4,7,3
97,98,31,0,Marketing,Assistant,599.40,22,3,9,2
98,99,53,0,Marketing,Executive,674.40,23,3,5,3
99,100,52,1,IT,Analyst,174.66,3,1,2,4