In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("Iris.csv")

In [3]:
df.shape

(150, 6)

In [4]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [7]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [8]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.groupby("Species").agg(['mean','median','max','min','std','quantile'])

                    Id                                     SepalLengthCm  \
                  mean median  max  min       std quantile          mean
Species
Iris-setosa       25.5   25.5   50    1  14.57738     25.5         5.006
Iris-versicolor   75.5   75.5  100   51  14.57738     75.5         5.936
Iris-virginica   125.5  125.5  150  101  14.57738    125.5         6.588

                                  ... PetalLengthCm                          \
                median  max  min  ...           max  min       std quantile
Species                           ...
Iris-setosa        5.0  5.8  4.3  ...           1.9  1.0  0.173511     1.50
Iris-versicolor    5.9  7.0  4.9  ...           5.1  3.0  0.469911     4.35
Iris-virginica     6.5  7.9  4.9  ...           6.9  4.5  0.551895     5.55

                PetalWidthCm
                        mean median  max  min       std quantile
Species
Iris-setosa            0.244    0.2  0.6  0.1  0.107210      0.2
Iris-versicolor        1.326    1.3  1.8  1.0  0.197753      1.3
Iris-virginica         2.026    2.0  2.5  1.4  0.274650      2.0

[3 rows x 30 columns]

In [11]:
df.groupby("Species").describe()

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [12]:
df.groupby("Species").describe()

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [13]:
df.groupby("Species").quantile([0.25,0.5,0.75])

                          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa     0.25   13.25          4.800         3.125          1.400
                0.50   25.50          5.000         3.400          1.500
                0.75   37.75          5.200         3.675          1.575
Iris-versicolor 0.25   63.25          5.600         2.525          4.000
                0.50   75.50          5.900         2.800          4.350
                0.75   87.75          6.300         3.000          4.600
Iris-virginica  0.25  113.25          6.225         2.800          5.100
                0.50  125.50          6.500         3.000          5.550
                0.75  137.75          6.900         3.175          5.875

                      PetalWidthCm
Species
Iris-setosa     0.25           0.2
                0.50           0.2
                0.75           0.3
Iris-versicolor 0.25           1.2
                0.50           1.3
                0.75           1.5
Iris-virginica  0.25           1.8
                0.50           2.0
                0.75           2.3